### ISSUE TITLE
[mime] Legacy Refactoring Task List

### ISSUE THREAD

**Issue by mi-hye** [codesquad-members-2024/fe-eventloop#16]
- [x] 1. 분석 후 리펙토링
_수요일까지 예상_
- [x] 2. 테스트 코드 작성
_하루만 투자(수 or 목)_
- [x] 3. 애니메이션 rAF방식으로 변경
- [x] 4. 기능 추가 : 동작취소 / 튜토리얼 추가
_3,4 합해서 하루만 투자(목 or 금)_
